kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-gerrit"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-gerrit"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-gerrit"
  apiGroup: rbac.authorization.k8s.io
