apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gerrit
  namespace: ci
spec:
  replicas: 1
  serviceName: mygerrit
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      initContainers:
      - name: busybox-gerrit-prepare-pvc
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "--"]
        args: ["chmod 777 /nfs/*; for file in gerrit.config secure.config; do [ -e /nfs/etc/$file ] || wget https://raw.githubusercontent.com/VictorYou/ci_study/master/app_gerrit/$file -O /nfs/etc/$file ; done; for file in gerritadmin.ldif developer1.ldif; do [ -e /nfs/etc/$file ] || wget https://raw.githubusercontent.com/VictorYou/ci_study/master/app_gerrit/$file -O /nfs/etc/$file; done"]
        volumeMounts:
        - name: gerrit-etc
          mountPath: /nfs/etc
        - name: gerrit-git
          mountPath: /nfs/git
        - name: gerrit-db
          mountPath: /nfs/db
        - name: gerrit-index
          mountPath: /nfs/index
        - name: gerrit-cache
          mountPath: /nfs/cache
      - name: busybox-gerrit-create-entry
        image: viyou/busybox:1.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "--"]
        args: ["while [ $(kubectl -n ci get po --selector=app=ldap -o jsonpath='{.items[0].status.containerStatuses[?(@.name==\"openldap\")].ready}') = true ]; do sleep 5; done; for file in gerritadmin.ldif developer1.ldif; do ldapadd -x -H ldap://myldap:7389 -D cn=admin,dc=example,dc=org -w secret -f /nfs/etc/$file; done"]
        volumeMounts:
        - name: gerrit-etc
          mountPath: /nfs/etc
      containers:
      - name: gerrit
        image: gerritcodereview/gerrit:3.2.3
        imagePullPolicy: IfNotPresent
        env:
        - name: CANONICAL_WEB_URL
          value: http://localhost
        ports:
        - containerPort: 29418
        - containerPort: 8080
        volumeMounts:
        - name: gerrit-etc
          mountPath: /var/gerrit/etc
        - name: gerrit-git
          mountPath: /var/gerrit/git
        - name: gerrit-db
          mountPath: /var/gerrit/db
        - name: gerrit-index
          mountPath: /var/gerrit/index
        - name: gerrit-cache
          mountPath: /var/gerrit/cache
      volumes:
      - name: gerrit-etc
        persistentVolumeClaim:
          claimName: gerrit-etc
          readOnly: false
      - name: gerrit-git
        persistentVolumeClaim:
          claimName: gerrit-git
          readOnly: false
      - name: gerrit-db
        persistentVolumeClaim:
          claimName: gerrit-db
          readOnly: false
      - name: gerrit-index
        persistentVolumeClaim:
          claimName: gerrit-index
          readOnly: false
      - name: gerrit-cache
        persistentVolumeClaim:
          claimName: gerrit-cache
          readOnly: false
