apiVersion: v1
kind: Service
metadata:
  name: gerrit
  namespace: ci
  labels:
    app: gerrit
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 29418
    targetPort: 29418
    nodePort: 32418
  - name: http
    port: 80 
    targetPort: 8080
    nodePort: 32080
  selector:
    app: gerrit
