apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-var
  namespace: ci
spec:
  storageClassName: rook-nfs-share-ldap-var
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-etc
  namespace: ci
spec:
  storageClassName: rook-nfs-share-ldap-etc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      initContainers:
      - name: busybox-ldap
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "--"]
        args: ["rm -rf /nfs/var/*; rm -rf /nfs/etc/*"]
        volumeMounts:
        - name: ldap-var
          mountPath: /nfs/var
        - name: ldap-etc
          mountPath: /nfs/etc
      containers:
      - name: openldap
        image: osixia/openldap:1.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LDAP_ADMIN_PASSWORD
          value: secret
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "ldapsearch -D cn=admin,dc=example,dc=org -w secret -b 'dc=example,dc=org' '(objectclass=*)'"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 100
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 389
        - containerPort: 636
        volumeMounts:
        - name: ldap-var
          mountPath: /var/lib/ldap
        - name: ldap-etc
          mountPath: /etc/ldap/slapd.d
      - name: ldap-admin
        image: osixia/phpldapadmin:0.9.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: localhost
        ports:
        - containerPort: 443
      volumes:
      - name: ldap-var
        persistentVolumeClaim:
          claimName: ldap-var
      - name: ldap-etc
        persistentVolumeClaim:
          claimName: ldap-etc
---
apiVersion: v1
kind: Service
metadata:
  name: myldap
  namespace: ci
  labels:
    app: ldap
spec:
  type: NodePort
  ports:
  - name: openldap
    port: 389
    targetPort: 389
    nodePort: 32389
  - name: ldap-admin
    port: 7443
    targetPort: 443
    nodePort: 32743
  selector:
    app: ldap
