apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-var
  namespace: ci
spec:
  storageClassName: rook-nfs-share-ldap-var
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-etc
  namespace: ci
spec:
  storageClassName: rook-nfs-share-ldap-etc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-ldap
  namespace: ci
  labels:
    app: pvc-ldap
spec:
  containers:
  - name: busybox-ldap
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "--"]
    args: ["rm -rf /nfs/var/*; rm -rf /nfs/etc/*; cat"]
    tty: true
    volumeMounts:
    - name: ldap-var
      mountPath: /nfs/var
    - name: ldap-etc
      mountPath: /nfs/etc
  volumes:
  - name: ldap-var
    persistentVolumeClaim:
      claimName: ldap-var
      readOnly: false
  - name: ldap-etc
    persistentVolumeClaim:
      claimName: ldap-etc
      readOnly: false
