apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-etc
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs-share-gerrit-etc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-git
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs-share-gerrit-git
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-db
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs-share-gerrit-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-index
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs-share-gerrit-index
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-cache
  namespace: ci
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-nfs-share-gerrit-cache
