apiVersion: v1
kind: Namespace
metadata:
  name: rook-nfs-ldap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-nfs-server
  namespace: rook-nfs-ldap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-ldap-etc
  namespace: rook-nfs-ldap
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-ldap-var
  namespace: rook-nfs-ldap
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs-ldap
  namespace: rook-nfs-ldap
spec:
  replicas: 1
  exports:
  - name: share-ldap-etc
    server:
      accessMode: ReadWrite
      squash: "none"
    persistentVolumeClaim:
      claimName: nfs-claim-ldap-etc
  - name: share-ldap-var
    server:
      accessMode: ReadWrite
      squash: "none"
    persistentVolumeClaim:
      claimName: nfs-claim-ldap-var
  annotations:
    rook: nfs
