apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  namespace: ci
spec:
  serviceName: myldap
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: LDAP_ADMIN_PASSWORD
          value: secret
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "ldapsearch -D cn=admin,dc=example,dc=org -w secret -b 'dc=example,dc=org' '(objectclass=*)'"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 100
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 389
        - containerPort: 636
        volumeMounts:
        - name: ldap-var
          mountPath: /var/lib/ldap
        - name: ldap-etc
          mountPath: /etc/ldap/slapd.d
      - name: ldap-admin
        image: osixia/phpldapadmin:0.9.0
        imagePullPolicy: IfNotPresent
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: localhost
        ports:
        - containerPort: 443
      volumes:
      - name: ldap-var
        persistentVolumeClaim:
          claimName: ldap-var
      - name: ldap-etc
        persistentVolumeClaim:
          claimName: ldap-etc
